package test:plugins;

interface plugin-i {
    resource plugin {
        name: func() -> string;
    }
}

interface factory {
    use plugin-i.{plugin};
    create: func() -> plugin;
}

interface factory2 {
    use plugin-i.{plugin};
    create: func() -> plugin;
}

world plugin {
    export plugin-i;
    export factory;
}

world plugin2 {
    export plugin-i;
    export factory2;
}

world app {
    import factory;
}

world app2 {
    import factory;
    import factory2;
}

world adapter {
    import factory;
    export factory2;
}
